# Generated by Django 4.2.6 on 2023-11-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='born_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='date',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='path',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
