# Generated by Django 4.2.6 on 2023-11-14 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_artist_slug_alter_artwork_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='collection.artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='collection.genre'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='collection.period'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='collection.style'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
